---
- name: Register list of cores we're supposed to have
  stat:
    path: "{{ solr_home }}/data/{{ item.name }}"
  register: list_of_cores
  with_items: "{{ solr_cores }}"

- name: Create directory for any new cores
  file:
    path: "{{ solr_home }}/data/{{ item.name }}"
    state: directory
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    recurse: true
  when: "item.name not in list_of_cores.results"
  with_items: "{{ solr_cores }}"

- name: Clone conf for new cores
  git:
    repo: "{{ item.conf_repo }}"
    dest: /var/solr/data/{{ item.name }}
    version: "{{ item.conf_version }}"
  when: "item.name not in list_of_cores.results"
  with_items: "{{ solr_cores }}"
  become: true
  become_user: "{{ solr_user }}"

- name: Update conf for existing cores
  git:
    repo: "{{ item.conf_repo }}"
    dest: /var/solr/data/{{ item.name }}
    version: "{{ item.conf_version }}"
    clone: no
    update: yes
  when: "item.name in list_of_cores.results"
  with_items: "{{ solr_cores }}"
  become: true
  become_user: "{{ solr_user }}"
