- name: Copy Jetty XML
  template:
    src: "jetty.xml.j2"
    dest: "/opt/solr/server/etc/jetty.xml"
    mode: 0644

- name: Copy Jetty default web xml
  template:
    src: "webdefault.xml.j2"
    dest: "/opt/solr/server/etc/webdefault.xml"
    mode: 0644

- name: Copy Solr specific web xml
  template:
    src: "web.xml.j2"
    dest: "/opt/solr/server/solr-webapp/webapp/WEB-INF/web.xml"
    mode: 0644

- name: Copy Realm properties file
  template:
    src: "realm.properties.j2"
    dest: "/opt/solr/server/realm.properties"
    mode: 0644
